"""Outcome tests for pi_docsite.generate, run against a temporary docs/ tree."""

from __future__ import annotations

import json
import logging
import tomllib
from pathlib import Path
from typing import Any

import pi_docsite.generate as generate_docs
import pytest
from pytest import MonkeyPatch


def _fake_home(target: Path) -> Any:
    """Patch Path.home() to a temp dir so detection never reads the real home."""
    return classmethod(lambda _cls: target)


FRONT = "---\nnav_group: Group\nnav_order: 10\n---\n"
DEFAULT_GROUP = "More"


def test_h1_ignores_inline_code_before_heading() -> None:
    assert generate_docs._h1("`inline code`\n# Title\n", "example") == "Title"


def _setup(tmp_path: Path, monkeypatch: MonkeyPatch, slugs: list[str]) -> Path:
    docs = tmp_path / "docs"
    docs.mkdir()
    for slug in slugs:
        # Every page carries its own nav_group; the generator must never need a
        # list inside the script to know which pages exist.
        (docs / f"{slug}.md").write_text(FRONT + f"# {slug.title()}\n\nBody of {slug}.\n", encoding="utf-8")
    # Artefacts the generator must never touch.
    (docs / "assets").mkdir()
    (docs / "assets" / "style.css").write_text("body{}\n", encoding="utf-8")
    (docs / ".nojekyll").touch()
    monkeypatch.setattr(generate_docs, "DOCS_DIR", docs)
    return docs


def test_main_writes_pages_and_indexes(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha", "beta"])

    assert generate_docs.main([]) == 0

    for name in ["index.html", "alpha.html", "beta.html", "search-index.json", "llms.txt", "llms-full.txt"]:
        assert (docs / name).is_file(), f"{name} was not generated"
    assert "Body of beta." in (docs / "beta.html").read_text(encoding="utf-8")
    assert "alpha.md" in (docs / "llms.txt").read_text(encoding="utf-8")
    search_index = json.loads((docs / "search-index.json").read_text(encoding="utf-8"))
    assert {entry["slug"] for entry in search_index} == {"alpha", "beta"}


def test_main_removes_only_its_own_stale_html(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    """A repo adopting the package may keep a hand-written 404.html or a
    search-engine verification file; those must survive."""
    docs = _setup(tmp_path, monkeypatch, ["alpha", "beta"])
    (docs / "orphan.html").write_text("<html>stale</html>\n<!-- generated by pi-docsite -->\n", encoding="utf-8")
    (docs / "404.html").write_text("<html>hand written</html>\n", encoding="utf-8")
    (docs / "google-verification.html").write_text("<html>meta</html>\n", encoding="utf-8")

    assert generate_docs.main([]) == 0

    assert not (docs / "orphan.html").exists(), "our own stale page should go"
    assert (docs / "404.html").is_file(), "hand-written 404 must be preserved"
    assert (docs / "google-verification.html").is_file(), "verification file must be preserved"


def test_main_preserves_sources_and_unrelated_assets(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha"])

    assert generate_docs.main([]) == 0

    assert (docs / "alpha.md").is_file()
    assert (docs / "assets" / "style.css").is_file()
    assert (docs / ".nojekyll").is_file()
    assert (docs / "index.html").is_file()


def test_generated_pages_carry_the_marker(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha"])

    assert generate_docs.main([]) == 0

    assert "generated by pi-docsite" in (docs / "alpha.html").read_text(encoding="utf-8")


def test_main_includes_a_page_that_has_no_frontmatter(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    """A page must never be silently dropped for lack of nav metadata."""
    docs = _setup(tmp_path, monkeypatch, ["alpha"])
    (docs / "plain.md").write_text("# Plain\n\nNo frontmatter here.\n", encoding="utf-8")

    assert generate_docs.main([]) == 0

    assert (docs / "plain.html").is_file()
    search_index = json.loads((docs / "search-index.json").read_text(encoding="utf-8"))
    assert "plain" in {entry["slug"] for entry in search_index}
    assert "plain" in (docs / "index.html").read_text(encoding="utf-8")


def test_main_is_idempotent(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha", "beta"])
    assert generate_docs.main([]) == 0
    first = {p.name: p.read_bytes() for p in docs.glob("*") if p.is_file()}
    assert generate_docs.main([]) == 0
    second = {p.name: p.read_bytes() for p in docs.glob("*") if p.is_file()}
    assert first == second


def test_skill_notice_names_the_packaged_skill_when_absent(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha"])
    notice = generate_docs._skill_notice(docs, home=tmp_path / "home")
    assert notice is not None
    assert "SKILL.md" in notice


@pytest.mark.parametrize(
    "relative",
    [
        ".agents/skills/pi-docsite",
        ".pi/agent/skills/pi-docsite",
        ".claude/skills/pi-docsite",
        ".cursor/skills/pi-docsite",
        ".gemini/skills/pi-docsite",
    ],
)
def test_skill_notice_is_silent_for_each_documented_home_location(
    tmp_path: Path, monkeypatch: MonkeyPatch, relative: str
) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha"])
    home = tmp_path / "home"
    installed = home / relative
    installed.mkdir(parents=True)
    (installed / "SKILL.md").write_text("# pi-docsite", encoding="utf-8")
    assert generate_docs._skill_notice(docs, home=home) is None


def test_skill_notice_is_silent_for_a_project_local_install(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha"])
    local = docs.parent / ".pi" / "skills" / "pi-docsite"
    local.mkdir(parents=True)
    (local / "SKILL.md").write_text("# pi-docsite", encoding="utf-8")
    assert generate_docs._skill_notice(docs, home=tmp_path / "home") is None


def test_skill_notice_debug_log_carries_the_detection_result(
    tmp_path: Path, monkeypatch: MonkeyPatch, caplog: pytest.LogCaptureFixture
) -> None:
    # A dict passed as the format argument leaves the formatted message without
    # any values, so an unexpected notice could not be explained from the log.
    docs = _setup(tmp_path, monkeypatch, ["alpha"])
    home = tmp_path / "home"
    installed = home / ".claude" / "skills" / "pi-docsite"
    installed.mkdir(parents=True)
    (installed / "SKILL.md").write_text("# pi-docsite", encoding="utf-8")

    with caplog.at_level(logging.DEBUG, logger="pi_docsite.generate"):
        assert generate_docs._skill_notice(docs, home=home) is None
    message = caplog.records[-1].getMessage()
    assert "candidates=6" in message
    assert str(installed) in message


def test_cli_badge_label_reaches_the_index(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha"])
    monkeypatch.setattr(generate_docs.Path, "home", _fake_home(tmp_path / "home"))

    assert generate_docs.main(["--badge-label", "acme-docs"]) == 0
    assert '⚡ acme<span class="brand-accent">-docs</span>' in (docs / "index.html").read_text(encoding="utf-8")


def test_cli_badge_label_reaches_a_content_page(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha"])
    monkeypatch.setattr(generate_docs.Path, "home", _fake_home(tmp_path / "home"))

    assert generate_docs.main(["--badge-label", "acme-docs"]) == 0
    assert '⚡ acme<span class="brand-accent">-docs</span>' in (docs / "alpha.html").read_text(encoding="utf-8")


def test_cli_badge_label_does_not_leak_into_the_next_build(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    # BADGE_LABEL doubled as the parser default, so one custom-label build made
    # that label sticky for every later in-process main() call.
    docs = _setup(tmp_path, monkeypatch, ["alpha"])
    monkeypatch.setattr(generate_docs.Path, "home", _fake_home(tmp_path / "home"))

    assert generate_docs.main(["--badge-label", "acme"]) == 0
    assert generate_docs.main([]) == 0
    html = (docs / "index.html").read_text(encoding="utf-8")
    assert "acme" not in html
    assert '⚡ pi<span class="brand-accent">-docsite</span>' in html


def test_published_packages_declare_a_readme() -> None:
    # Both PyPI wheels shipped an empty long_description until `readme` was added.
    root = Path(__file__).resolve().parents[3]
    for rel in ("packages/pi-docsite/pyproject.toml", "packages/pi-sidecar/pyproject.toml"):
        data = tomllib.loads((root / rel).read_text(encoding="utf-8"))
        readme = data["project"].get("readme")
        assert readme, f"{rel} declares no readme, so its PyPI page has no description"
        assert (root / rel).parent.joinpath(readme).is_file(), f"{rel} points at a missing {readme}"
