"""Outcome tests for pi_docsite.generate, run against a temporary docs/ tree."""

from __future__ import annotations

import fnmatch
import json
import logging
import tomllib
from collections.abc import Sequence
from pathlib import Path
from typing import Any

import pi_docsite.generate as generate_docs
import pytest
from pytest import MonkeyPatch


def _fake_home(target: Path) -> Any:
    """Patch Path.home() to a temp dir so detection never reads the real home."""
    return classmethod(lambda _cls: target)


FRONT = "---\nnav_group: Group\nnav_order: 10\n---\n"
DEFAULT_GROUP = "More"


def test_h1_ignores_inline_code_before_heading() -> None:
    assert generate_docs._h1("`inline code`\n# Title\n", "example") == "Title"


def _setup(tmp_path: Path, monkeypatch: MonkeyPatch, slugs: list[str]) -> Path:
    docs = tmp_path / "docs"
    docs.mkdir()
    for slug in slugs:
        # Every page carries its own nav_group; the generator must never need a
        # list inside the script to know which pages exist.
        (docs / f"{slug}.md").write_text(FRONT + f"# {slug.title()}\n\nBody of {slug}.\n", encoding="utf-8")
    # Artefacts the generator must never touch.
    (docs / "assets").mkdir()
    (docs / "assets" / "style.css").write_text("body{}\n", encoding="utf-8")
    (docs / ".nojekyll").touch()
    monkeypatch.setattr(generate_docs, "DOCS_DIR", docs)
    return docs


def test_main_writes_pages_and_indexes(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha", "beta"])

    assert generate_docs.main([]) == 0

    for name in ["index.html", "alpha.html", "beta.html", "search-index.json", "llms.txt", "llms-full.txt"]:
        assert (docs / name).is_file(), f"{name} was not generated"
    assert "Body of beta." in (docs / "beta.html").read_text(encoding="utf-8")
    assert "alpha.md" in (docs / "llms.txt").read_text(encoding="utf-8")
    search_index = json.loads((docs / "search-index.json").read_text(encoding="utf-8"))
    assert {entry["slug"] for entry in search_index} == {"alpha", "beta"}


def test_main_removes_only_its_own_stale_html(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    """A repo adopting the package may keep a hand-written 404.html or a
    search-engine verification file; those must survive."""
    docs = _setup(tmp_path, monkeypatch, ["alpha", "beta"])
    (docs / "orphan.html").write_text("<html>stale</html>\n<!-- generated by pi-docsite -->\n", encoding="utf-8")
    (docs / "404.html").write_text("<html>hand written</html>\n", encoding="utf-8")
    (docs / "google-verification.html").write_text("<html>meta</html>\n", encoding="utf-8")

    assert generate_docs.main([]) == 0

    assert not (docs / "orphan.html").exists(), "our own stale page should go"
    assert (docs / "404.html").is_file(), "hand-written 404 must be preserved"
    assert (docs / "google-verification.html").is_file(), "verification file must be preserved"


def test_main_preserves_sources_and_unrelated_assets(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha"])

    assert generate_docs.main([]) == 0

    assert (docs / "alpha.md").is_file()
    assert (docs / "assets" / "style.css").is_file()
    assert (docs / ".nojekyll").is_file()
    assert (docs / "index.html").is_file()


def test_generated_pages_carry_the_marker(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha"])

    assert generate_docs.main([]) == 0

    assert "generated by pi-docsite" in (docs / "alpha.html").read_text(encoding="utf-8")


def test_main_includes_a_page_that_has_no_frontmatter(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    """A page must never be silently dropped for lack of nav metadata."""
    docs = _setup(tmp_path, monkeypatch, ["alpha"])
    (docs / "plain.md").write_text("# Plain\n\nNo frontmatter here.\n", encoding="utf-8")

    assert generate_docs.main([]) == 0

    assert (docs / "plain.html").is_file()
    search_index = json.loads((docs / "search-index.json").read_text(encoding="utf-8"))
    assert "plain" in {entry["slug"] for entry in search_index}
    assert "plain" in (docs / "index.html").read_text(encoding="utf-8")


def test_main_is_idempotent(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha", "beta"])
    assert generate_docs.main([]) == 0
    first = {p.name: p.read_bytes() for p in docs.glob("*") if p.is_file()}
    assert generate_docs.main([]) == 0
    second = {p.name: p.read_bytes() for p in docs.glob("*") if p.is_file()}
    assert first == second


def test_skill_notice_names_the_packaged_skill_when_absent(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha"])
    notice = generate_docs._skill_notice(docs, home=tmp_path / "home")
    assert notice is not None
    assert "SKILL.md" in notice


@pytest.mark.parametrize(
    "relative",
    [
        ".agents/skills/pi-docsite",
        ".pi/agent/skills/pi-docsite",
        ".claude/skills/pi-docsite",
        ".cursor/skills/pi-docsite",
        ".gemini/skills/pi-docsite",
    ],
)
def test_skill_notice_is_silent_for_each_documented_home_location(
    tmp_path: Path, monkeypatch: MonkeyPatch, relative: str
) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha"])
    home = tmp_path / "home"
    installed = home / relative
    installed.mkdir(parents=True)
    (installed / "SKILL.md").write_text("# pi-docsite", encoding="utf-8")
    assert generate_docs._skill_notice(docs, home=home) is None


def test_skill_notice_is_silent_for_a_project_local_install(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha"])
    local = docs.parent / ".pi" / "skills" / "pi-docsite"
    local.mkdir(parents=True)
    (local / "SKILL.md").write_text("# pi-docsite", encoding="utf-8")
    assert generate_docs._skill_notice(docs, home=tmp_path / "home") is None


def test_skill_notice_debug_log_carries_the_detection_result(
    tmp_path: Path, monkeypatch: MonkeyPatch, caplog: pytest.LogCaptureFixture
) -> None:
    # A dict passed as the format argument leaves the formatted message without
    # any values, so an unexpected notice could not be explained from the log.
    docs = _setup(tmp_path, monkeypatch, ["alpha"])
    home = tmp_path / "home"
    installed = home / ".claude" / "skills" / "pi-docsite"
    installed.mkdir(parents=True)
    (installed / "SKILL.md").write_text("# pi-docsite", encoding="utf-8")

    with caplog.at_level(logging.DEBUG, logger="pi_docsite.generate"):
        assert generate_docs._skill_notice(docs, home=home) is None
    message = caplog.records[-1].getMessage()
    assert "candidates=6" in message
    assert str(installed) in message


def test_cli_badge_label_reaches_the_index(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha"])
    monkeypatch.setattr(generate_docs.Path, "home", _fake_home(tmp_path / "home"))

    assert generate_docs.main(["--badge-label", "acme-docs"]) == 0
    assert '⚡ acme<span class="brand-accent">-docs</span>' in (docs / "index.html").read_text(encoding="utf-8")


def test_cli_badge_label_reaches_a_content_page(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha"])
    monkeypatch.setattr(generate_docs.Path, "home", _fake_home(tmp_path / "home"))

    assert generate_docs.main(["--badge-label", "acme-docs"]) == 0
    assert '⚡ acme<span class="brand-accent">-docs</span>' in (docs / "alpha.html").read_text(encoding="utf-8")


def test_cli_badge_label_does_not_leak_into_the_next_build(tmp_path: Path, monkeypatch: MonkeyPatch) -> None:
    # BADGE_LABEL doubled as the parser default, so one custom-label build made
    # that label sticky for every later in-process main() call.
    docs = _setup(tmp_path, monkeypatch, ["alpha"])
    monkeypatch.setattr(generate_docs.Path, "home", _fake_home(tmp_path / "home"))

    assert generate_docs.main(["--badge-label", "acme"]) == 0
    assert generate_docs.main([]) == 0
    html = (docs / "index.html").read_text(encoding="utf-8")
    assert "acme" not in html
    assert '⚡ pi<span class="brand-accent">-docsite</span>' in html


def test_published_packages_declare_a_readme() -> None:
    # Both PyPI wheels shipped an empty long_description until `readme` was added.
    root = Path(__file__).resolve().parents[3]
    for rel in ("packages/pi-docsite/pyproject.toml", "packages/pi-sidecar/pyproject.toml"):
        data = tomllib.loads((root / rel).read_text(encoding="utf-8"))
        readme = data["project"].get("readme")
        assert readme, f"{rel} declares no readme, so its PyPI page has no description"
        assert (root / rel).parent.joinpath(readme).is_file(), f"{rel} points at a missing {readme}"


# What one build of a two-page site writes: the pages, the copied assets and the
# three root-level files. _review_notice is given this list explicitly, because
# "what this build wrote" is exactly the contract under test.
GENERATED = ["index.html", "alpha.html", "assets/style.css", "assets/search.js", "llms.txt", "search-index.json"]


def _review_config(root: Path, body: str) -> Path:
    config = root / generate_docs.REVIEW_CONFIG
    config.write_text(body, encoding="utf-8")
    return config


def _notice(docs: Path, generated: Sequence[str] = GENERATED) -> str | None:
    config = generate_docs._find_review_config(docs)
    assert config is not None, "no review config found for the test"
    return generate_docs._review_notice(docs, generated, config)


def test_review_notice_is_silent_without_a_review_config(tmp_path: Path) -> None:
    assert generate_docs._find_review_config(tmp_path / "docs") is None


def test_review_notice_names_the_patterns_when_generated_files_are_in_scope(tmp_path: Path) -> None:
    docs = tmp_path / "docs"
    docs.mkdir()
    _review_config(tmp_path, "[config]\nadd_repo_metadata = true\n")

    notice = _notice(docs)
    assert notice is not None
    assert "[ignore]" in notice
    # HTML is the compact pattern while nothing else in the directory is hand-written.
    assert '"docs/*.html"' in notice
    # Assets and root files are named one by one: docs/assets/ is shared.
    assert '"docs/assets/style.css"' in notice
    assert '"docs/llms.txt"' in notice
    assert '"docs/search-index.json"' in notice
    # The .md sources are the repo's own work and must stay in review scope.
    assert "docs/*.md" not in notice


def test_review_notice_keeps_preserved_html_in_review(tmp_path: Path) -> None:
    # A repo may keep a hand-written 404.html or a verification page -- the
    # generator preserves both -- so a blanket docs/*.html would hide them too.
    docs = tmp_path / "docs"
    docs.mkdir()
    (docs / "404.html").write_text("<html><body>Not found</body></html>\n", encoding="utf-8")
    _review_config(tmp_path, "[config]\n")

    notice = _notice(docs)
    assert notice is not None
    assert '"docs/*.html"' not in notice
    assert '"docs/index.html"' in notice
    assert "404.html" not in notice


def test_review_notice_tells_the_user_to_merge_into_an_existing_table(tmp_path: Path) -> None:
    # A second [ignore] table is invalid TOML, and the parse-failure branch would
    # then silence this notice for good.
    docs = tmp_path / "docs"
    docs.mkdir()
    _review_config(tmp_path, '[ignore]\nglob = ["vendor/*"]\n')

    notice = _notice(docs)
    assert notice is not None
    assert "existing [ignore].glob list" in notice
    # The suggestion must paste into a config that already has the table, keeping
    # the existing entry: the result still parses and still silences the notice.
    array = notice.split("\n\n", 1)[1].removeprefix("# inside [ignore].glob:\n").strip()
    merged = tmp_path / "merged.toml"
    merged.write_text(f'[ignore]\nglob = ["vendor/*", {array[1:-1]}]\n', encoding="utf-8")
    parsed = tomllib.loads(merged.read_text(encoding="utf-8"))["ignore"]["glob"]
    assert parsed[0] == "vendor/*"
    assert "docs/*.html" in parsed
    assert generate_docs._review_notice(docs, GENERATED, merged) is None


def test_review_notice_is_silent_once_the_config_covers_the_generated_files(tmp_path: Path) -> None:
    docs = tmp_path / "docs"
    docs.mkdir()
    config = _review_config(
        tmp_path,
        '[ignore]\nglob = ["docs/*.html", "docs/assets/*", "docs/llms.txt", "docs/search-index.json"]\n',
    )
    assert generate_docs._review_notice(docs, GENERATED, config) is None


def test_review_notice_ignores_an_unrelated_ignore_list(tmp_path: Path) -> None:
    docs = tmp_path / "docs"
    docs.mkdir()
    # Basename-only globs match repo-relative paths, so this covers nothing.
    _review_config(tmp_path, '[ignore]\nglob = ["*.html", "llms.txt"]\n')
    assert _notice(docs) is not None
    # docs/** does cover the generated files (fnmatch: * spans "/"), so a repo
    # that chose the blunt option is left alone -- the notice is about coverage,
    # not about taste.
    _review_config(tmp_path, '[ignore]\nglob = ["docs/**"]\n')
    assert _notice(docs) is None


@pytest.mark.parametrize("glob", ["1", '"docs/*.html"', "true"])
def test_review_notice_survives_an_unusable_glob_value(tmp_path: Path, glob: str) -> None:
    # None of these shapes is reviewable config. Matched blindly, [1] raises
    # TypeError after the site is written and a bare string matches character by
    # character -- the worst outcome, a build that aborts or a notice that never
    # comes back.
    docs = tmp_path / "docs"
    docs.mkdir()
    _review_config(tmp_path, f"[ignore]\nglob = {glob}\n")
    assert _notice(docs) is not None


def test_review_notice_stays_quiet_on_an_unparsable_config(tmp_path: Path) -> None:
    docs = tmp_path / "docs"
    docs.mkdir()
    config = _review_config(tmp_path, "not = = toml\n")
    assert generate_docs._review_notice(docs, GENERATED, config) is None


def test_review_notice_finds_the_config_beside_a_symlinked_docs_dir(tmp_path: Path) -> None:
    # main() resolves --docs-dir for file operations; the config still sits next
    # to the symlink, which is what the review tool reads.
    elsewhere = tmp_path / "elsewhere" / "site"
    elsewhere.mkdir(parents=True)
    (tmp_path / "docs").symlink_to(elsewhere)
    config = _review_config(tmp_path, "[config]\n")

    assert generate_docs._find_review_config(tmp_path / "docs") == config


def test_review_notice_prints_repo_relative_globs_for_a_symlinked_docs_dir(tmp_path: Path) -> None:
    # main() resolves --docs-dir for file operations, but the printed paths are
    # matched against repo-relative ones: with docs/ pointing out of the repo,
    # the resolved path would yield absolute suggestions nothing can match.
    elsewhere = tmp_path / "elsewhere" / "site"
    elsewhere.mkdir(parents=True)
    (tmp_path / "docs").symlink_to(elsewhere)
    config = _review_config(tmp_path, "[config]\n")

    notice = generate_docs._review_notice(tmp_path / "docs", GENERATED, config, on_disk=elsewhere)
    assert notice is not None
    assert '"docs/*.html"' in notice
    assert str(tmp_path) not in notice


def test_review_notice_omits_the_dot_prefix_when_docs_is_the_repo_root(tmp_path: Path) -> None:
    # relative_to() yields "." when both paths are the repo root, and
    # "./index.html" is not what the review tool matches.
    _review_config(tmp_path, "[config]\n")

    notice = generate_docs._review_notice(tmp_path, GENERATED, tmp_path / generate_docs.REVIEW_CONFIG)
    assert notice is not None
    assert '"./index.html"' not in notice
    assert '"*.html"' in notice
    assert "under the docs root" in notice
    # And the suggestion really does silence the notice once pasted.
    config = tmp_path / "covered.toml"
    array = notice.split("\n\n", 1)[1].removeprefix("[ignore]\nglob = ").strip()
    config.write_text(f"[ignore]\nglob = {array}\n", encoding="utf-8")
    assert generate_docs._review_notice(tmp_path, GENERATED, config) is None


def test_review_notice_escapes_glob_metacharacters_in_page_names(tmp_path: Path) -> None:
    # A page may be called guide[1].html. Unescaped, the brackets are a
    # character class and the suggestion stops matching the file it was meant to
    # exclude, so the notice comes back on every build.
    docs = tmp_path / "docs"
    docs.mkdir()
    (docs / "404.html").write_text("<html><body>Not found</body></html>\n", encoding="utf-8")
    _review_config(tmp_path, "[config]\n")
    generated = ["index.html", "guide[1].html", "search-index.json"]

    notice = _notice(docs, generated)
    assert notice is not None
    assert '"docs/guide[[]1[]].html"' in notice
    # The escaped pattern matches the literal file, which is what silences it.
    assert fnmatch.fnmatch("docs/guide[1].html", "docs/guide[[]1[]].html")


def test_review_notice_finds_the_config_above_a_nested_docs_dir(tmp_path: Path) -> None:
    docs = tmp_path / "website" / "docs"
    docs.mkdir(parents=True)
    config = _review_config(tmp_path, "[config]\n")

    assert generate_docs._find_review_config(docs) == config
    notice = generate_docs._review_notice(docs, GENERATED, config)
    # The globs are matched against repo-relative paths, so the prefix is the
    # docs dir's own location under the repo root, not "docs".
    assert notice is not None
    assert '"website/docs/*.html"' in notice


def test_review_notice_debug_log_carries_the_missing_files(tmp_path: Path, caplog: pytest.LogCaptureFixture) -> None:
    docs = tmp_path / "docs"
    docs.mkdir()
    config = _review_config(tmp_path, '[ignore]\nglob = ["docs/*.html"]\n')

    with caplog.at_level(logging.DEBUG, logger="pi_docsite.generate"):
        assert generate_docs._review_notice(docs, GENERATED, config) is not None
    message = caplog.records[-1].getMessage()
    assert "docs/llms.txt" in message
    assert "docs/alpha.html" not in message


def test_main_prints_the_review_notice_beside_the_summary(
    tmp_path: Path, monkeypatch: MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    docs = _setup(tmp_path, monkeypatch, ["alpha"])
    _review_config(docs.parent, "[config]\n")

    assert generate_docs.main([]) == 0

    out = capsys.readouterr().out
    assert "[ignore]" in out
    assert '"docs/alpha.html"' in out or '"docs/*.html"' in out


def test_main_says_nothing_when_the_repo_has_no_review_config(
    tmp_path: Path, monkeypatch: MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    _setup(tmp_path, monkeypatch, ["alpha"])

    assert generate_docs.main([]) == 0

    assert "[ignore]" not in capsys.readouterr().out
